name: Sync Code to Gitee
on:
# 如果需要PR触发把push前的#去掉
# push:
  schedule:
    - cron:  '0 */3 * * *'
jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: Yikun/hub-mirror-action@v0.08
      with:
        src: github/renbaoshuo
        dst: gitee/renbaoshuo
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: user
        # black_list: renbaoshuo.github.io

